### ISSUE TITLE
Error 'couldn't finish sparsification2522' at postprocessing step (hinge clip)

### ISSUE THREAD

**Issue by agroppi** [HingeAssembler/HINGE#111]
```
Run postprocessing:' Wed May 3 10:30:08 CEST 2017
Run postprocessing: Wed May 3 10:30:08 CEST 2017
+ /home/ag/HINGE/inst/bin/hinge clip Stella.edges.hinges Stella.hinge.list hinge_3kb
0 bad coverage reads.
0 bad self aligned reads.
couldn't finish sparsification2522
couldn't finish sparsification2522
```

Thanks

**Comment by ilanshom** [comment]
Typically `couldn't finish sparsification` isn't really an error. When we output the graphml files, we try to sparsify the graph so that it is smaller and easier to interpret. But sometimes, if the graph is too complicated our heuristic may not work, so we output that message.

But in principle this should not affect the rest of the pipeline.

**Comment by agroppi** [comment]
Hi,
Actually it does affects the rest of the pipeline.
Next step : 
```
'get draft assembly :' Wed May 3 13:10:29 CEST 2017
get draft assembly : Wed May 3 13:10:29 CEST 2017
+ /home/ag/HINGE/inst/bin/hinge draft-path /gpfs/scratch/ag/sWAGMAN/HINGE_Stella_fasta_3kb Stella Stellahinge_3kb.G2.graphml
Traceback (most recent call last):
  File "/home/ag/HINGE/inst/bin/../lib/hinge/get_draft_path.py", line 74, in <module>
    stdout=subprocess.PIPE,bufsize=1)
  File "/module/apps/python/2.7.12/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/module/apps/python/2.7.12/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```
I have : 
```
Stellahinge_3kb.G00.graphml  Stellahinge_3kb.G1.graphml   Stellahinge_3kb.G2.graphml   Stellahinge_3kb.Gc.graphml
Stellahinge_3kb.G0.graphml   Stellahinge_3kb.G2c.graphml  Stellahinge_3kb.G2s.graphml  Stellahinge_3kb.Gs.graphml
```

**Comment by fxia22** [comment]
It looks like you don't have directory of DBshow in your PATH environment. You can try call `DBShow` from shell to verify. You can use `utils/setup.sh` to set up the environment properly.
