### ISSUE TITLE
ini settings recomandation for plant genome

### ISSUE THREAD

**Issue by mictadlo** [HingeAssembler/HINGE#144]
Hi,
Do you have any settings recommendation for tetraploid plant genome?

Thank you in advance.

Michal

**Comment by ilanshom** [comment]
Hi Michal,
HINGE doesn't currently have capability of phasing polyploid genomes, so we don't have specific recommendations for a tetraploid plant genome. But we suggest that you use
`del_telomeres = 1` and `aggressive_pruning = 1` to simplify the final assembly graphs. In order to use aggressive_pruning you will need to use the latest commit of HINGE and add your ini file as a fourth argument to `hinge clip`; so you would have
```
hinge clip ecoli.edges.hinges ecoli.hinge.list test nominal.ini
```

**Comment by jwasmuth** [comment]
Hi @ilanshom,
When I add the .ini at the end of `hinge clip-nanopore`, I get the following error

`hinge clip-nanopore ecoli.edges.hinges ecoli.hinge.list demo giardia.ini`
> Traceback (most recent call last):
  File "/home/jwasmuth/bioinformatics/HINGE/inst/bin/../lib/hinge/pruning_and_clipping_nanopore.py", line 1214, in <module>
    add_groundtruth(G,json_file,in_hinges,out_hinges)
  File "/home/jwasmuth/bioinformatics/HINGE/inst/bin/../lib/hinge/pruning_and_clipping_nanopore.py", line 806, in add_groundtruth
    mapping = ujson.load(json_file)
ValueError: Unexpected character found when decoding 'false'

Thanks for any advice you have.
James

**Comment by ilanshom** [comment]
Hi James,
I just updated `hinge clip-nanopore`, and it should now be able to read the ini file. Let me know if things work with the latest commit.

**Comment by jwasmuth** [comment]
Hi @ilanshom, 
That worked too. Thanks!
I let you or the creator close this issue when appropriate. For what it's worth, I found the information about large genomes very useful and recommend adding it to a recipe list if one is planned.
Thanks again
James
