### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory /C.odor_temp_.G2.graphml'

### ISSUE THREAD

**Issue by jsimba-99** [HingeAssembler/HINGE#159]
Hi, Im not familiar with programing rather interested in long reads cp genome assembly from plant DNA
using Hinge I've got this error:

**Traceback (most recent call last):
  File "/home/sesinchi/Sinchi/45_hingue/HINGE//inst/bin/../lib/hinge/get_draft_path.py", line 59, in <module>
    in_graph = nx.read_graphml(graphml_path)
  File "/usr/local/lib/python3.6/site-packages/decorator-5.0.9-py3.6.egg/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/usr/local/lib/python3.6/site-packages/networkx-1.9-py3.6.egg/networkx/utils/decorators.py", line 198, in _open_file
    fobj = _dispatch_dict[ext](path, mode=mode)
FileNotFoundError: [Errno 2] No such file or directory: '/home/Jaime_S/Genomas_Cedrela/Hinge_results/C.odor/C.odor_temp_.G2.graphml'**

I followed different recommendations such as use network 1.9, python 3.6 

I would appreciate any comment or suggestion to fix this error

many thanks,

**Comment by fxia22** [comment]
Hi @jsimba-99, how large is this plant DNA? From our previous experience HINGE works the best for sequences on the order of 1-10M base pairs, so it might not scale to the plant genome you mentioned. 

Looks like the graph is not generated by a previous step.

**Comment by jsimba-99** [comment]
> Hi @jsimba-99, how large is this plant DNA? From our previous experience HINGE works the best for sequences on the order of 1-10M base pairs, so it might not scale to the plant genome you mentioned.
> 
> Looks like the graph is not generated by a previous step.

Hi  @fxia22, 

Im performing the assembly of a 156 kb chloroplast sequence using ONT seq reads and the corresponding lines of the script that fail are:

coverage='/home/Jaime_S/Genomas_Cedrela/Hinge_results/C.odor'

#get draft assembly

hinge draft-path . $coverage ${coverage}_temp_.G2.graphml


Thanks for your comments
