### ISSUE TITLE
TypeError: must be str, not bytes in parse_read.py script

### ISSUE THREAD

**Issue by jsimba-99** [HingeAssembler/HINGE#160]
Hi, running hinge to assemble the chloroplast genome (~156kb) of a plant species after install and set up all the dependencies and scripts I got the following error:

draft assembly
Traceback (most recent call last):
  File "/HINGE//inst/bin/../lib/hinge/get_draft_path.py", line 77, in <module>
    for read_id,read in zip(reads,reads_queried):
  File "/HINGE/inst/lib/hinge/parse_read.py", line 21, in parse_read
    seq += l.strip()
TypeError: must be str, not bytes

Everything seemed it was working up to this point 

I don't how to solve this error and would appreciate any help

Cheers,

**Comment by fxia22** [comment]
It should work if you change to `seq += l.decode('ascii').strip()` or `seq += l.decode('utf-8').strip()`.

**Comment by jsimba-99** [comment]
Thanks, it worked apparently

My line now shows this error:

 draft assembly
Traceback (most recent call last):
  File "/HINGE//inst/bin/../lib/hinge/get_draft_path.py", line 109, in <module>
    vert_len = len(read_dict[int(vert_id)][1])
KeyError: 844

Any idea about this?

Many thanks @fxia22

Cheers,
